### ISSUE TITLE
AIOInit for RPI

### ISSUE THREAD

**Issue by masterglob** [bitbank2/tm1637#2]
Currently, compiling on RPI (3+) and linking is OK but at run time the following issue is raised:
`
Unrecognized board type, aborting...
Error initializing ArmbianIO library
`
It is due to the fact that the call to `AIOInit()`, which calls `AIOInitBoard()` won't work in non-armbian OS...

I add to manually replace the init by 
`rc = AIOInitBoard("Raspberry Pi");`  in `tm1637Init`.

I don't know what is the cleanest solution... (I don't want to manually create `/run/machine.id` because does not seem very nice to me...)

**Comment by bitbank2** [comment]
You did it correctly. No need to change anything.

**Comment by masterglob** [comment]
Thanks for response !
